### ISSUE TITLE
Redis should use a connection pool

### ISSUE THREAD

**Issue by jamescasbon** [bottlepy/bottle-extras#10]
I posted a version here: 

https://gist.github.com/1870749

Otherwise it goes wrong after a certain number of open connections.

**Comment by sc68cal** [comment]
Can you fork bottle-extras and apply your patch, so that a pull request can be submitted? I want to give you proper attribute.

**Comment by jamescasbon** [comment]
Sure, will do.  Just edited the file on a installed file and wanted to
capture what I had done.

On Mon, Feb 20, 2012 at 7:51 PM, Sean M. Collins
reply@reply.github.com
wrote:

> Can you fork bottle-extras and apply your patch, so that a pull request can be submitted? I want to give you proper attribute.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bottlepy/bottle-extras/issues/10#issuecomment-4060507

## 

James Casbon

Population Genetics - http://www.populationgenetics.com/
james.casbon@populationgenetics.com
+44 (0)1223 497353

**Comment by jamescasbon** [comment]
See #11
