### ISSUE TITLE
Write a Memcache plugin

### ISSUE THREAD

**Issue by sc68cal** [bottlepy/bottle-extras#4]
While we have Redis already, we might want to toss in a plugin for Memcache too.

**Comment by sc68cal** [comment]
Well - first thing that I need to figure out is:

[Which client to use!?!?!?](http://code.google.com/p/memcached/wiki/Clients)

**Comment by thekad** [comment]
Hey, look at that, I somehow referenced the pull req in here :)

Anyway, my reasoning on using python-memcached? it is supported upstream in debian, ubuntu, fedora and I believe is pretty easy to install in all pip installs. Thoughts?

**Comment by sc68cal** [comment]
Looks good, although I think you may need to specify python-memcached as the package name in the setup.py file

Pulled down your fork and ran the tests, looks very good.

**Comment by thekad** [comment]
Funny story, using 'python-memcached' makes distutils unhappy. It all gets explained (although not that clearly) here: http://pydoc.org/2.5.1/distutils.versionpredicate.html TL;DR :

```
It the module or package name given does not conform to what's
allowed as a legal module or package name, `ValueError` is
raised::
>>> v = VersionPredicate('foo-bar')
Traceback (most recent call last):
```

I thought about using setuptools but it lacks support for python3 (something bottle is proud of offering), and dealing with distribute just seemed too much pain, but perhaps it is needed?

**Comment by sc68cal** [comment]
OK - we can tinker with it going forward.
